name: Deploy to Digital Ocean

on:
  push:
    branches:
      - [BRANCH NAME]

env:
  HOST: [HOST OR IP]
  USERNAME: [USERNAME]
  SSH_TARGET: [DEPLOYMENT FOLDER PATH]
  FIREWALL_NAME: [FIREWALL NAME]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Doorkeeper open
        uses: workhorsemarketing/digital-ocean-doorkeeper@master
        with:
          digitaloceanToken: ${{ secrets.WH_DO_FIREWALL_KEY }} 
          firewallName: ${{ env.FIREWALL_NAME }}
          actionToDo: "add"
          dryRun: false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: workhorsemarketing/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.WH_DO_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ env.HOST }}
          REMOTE_USER: ${{ env.USERNAME }}
          TARGET: "${{ env.SSH_TARGET }}"
          EXCLUDE: "/.github/, /.git/, /README.md, /.gitignore"
          # SCRIPT_BEFORE: |
            # whoami
            # ls -al
          SCRIPT_AFTER: |
            whoami
            composer install && php artisan migrate --force && npm install && npm run build && php artisan optimize:clear && php artisan queue:restart
            ls -al
            # echo $RSYNC_STDOUT

      - name: Doorkeeper close
        uses: workhorsemarketing/digital-ocean-doorkeeper@master
        with:
          digitaloceanToken: ${{ secrets.WH_DO_FIREWALL_KEY }} 
          firewallName: ${{ env.FIREWALL_NAME }}
          actionToDo: "remove"
          dryRun: false
